### ISSUE TITLE
Basic instalation

### ISSUE THREAD

**Issue by satorres** [kosoukhov/yii2-ldap#1]
How do I configure and install it on basic yii2 template?

**Comment by kosoukhov** [comment]
Hello!

Sorry for my long time response.

You can add the ldap.php file to the directory basic/config/ and write the code to it:

```
return [
    'class' => 'kosoukhov\ldap\Connector',
    'useCache' => YII_ENV_DEV ? false : true,
    'host' => 'ldap.example.com',
    'port' => '389',
    'baseDN' => 'OU=...,DC=...,DC=...,DC=net',
    'userDN' => '@....corp.net',
    'groupDN' => '',
    //Input your AD login/pass on dev or sys login/pass on test/prod servers
    'sysUserLogin' => '',
    'sysUserPassword' => '',
];
```

After that, add a line:
$ldap = require __DIR__ . '/ldap.php'; 
at the beginning of the file basic/config/web.php and in the components section:

```
$config = [
    //....
    'components' => [
    //....
        'ldap' => $ldap,
    ],
```
Look at how the configuration of the component for working with the database is made, this is the same.
